enum CacheControlScope {
  PUBLIC
  PRIVATE
}

directive @cacheControl(
  maxAge: Int
  scope: CacheControlScope
  inheritMaxAge: Boolean
) on FIELD_DEFINITION | OBJECT | INTERFACE | UNION

type Author @cacheControl(maxAge: 60){
  id: Int! 
  username: String
  books: [Book]
}

type Query{
  authors: [Author]
  author(id: Int!): Author
}